apiVersion: v1
kind: PersistentVolume
metadata:
    name: $PV_NAME
    namespace: $NAMESPACE_NAME
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: $STORAGE_SPACE
  hostPath:
    path: /data/mongo
