apiVersion: v1
kind: Service
metadata:
  name: $BACKEND_SERVICE_NAME
  namespace: $NAMESPACE_NAME
spec:
  ports:
    - port: 8081
      targetPort: $CONTAINER_PORT
  selector:
    app: $BACKEND_DEPLOYMENT_NAME