apiVersion: v1
kind: Pod
metadata:
  name: $REDIS_NAME
  namespace: $NAMESPACE_NAME
spec:
  containers:
  - name: $REDIS_NAME
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: $REDIS_CONFIG_NAME
        items:
        - key: redis-config
          path: redis.conf