apiVersion: v1
kind: Service
metadata:
    name: $NODEPORT_BACKEND_SERVICE_NAME
    namespace: $NAMESPACE_NAME
spec:
    ports:
    - name: $DEPLOYED_APP_NAME
      targetPort: $BACKEND_SERVICE_PORT
      port: $BACKEND_SERVICE_PORT
      nodePort: 30253
      protocol: TCP
    selector:
       app: $DEPLOYED_APP_NAME
    type: NodePort