apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $PV_CLAIM_NAME
  namespace: $NAMESPACE_NAME
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: $PV_NAME
  resources:
    requests:
      storage: $STORAGE_SPACE