# Create a ClusterIssuer resource that points to the Let's Encrypt staging API.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
  namespace: $NAMESPACE_NAME
spec:
  acme:
    server: $LETS_ENCRYPT_PRODUCTION_SERVER
    privateKeySecretRef:
      name: letsencrypt-stage-key
    email: $EMAIL_ADDRESS
    solvers:
      # - http01:
      #     ingress:
      #       class: traefik
      - dns01:
          route53:
            hostedZoneID: $HOSTED_ZONE_ID
            region: $AWS_REGION
            accessKeyID: $AWS_ACCESS_KEY_ID_FOR_ROUTE53
            secretAccessKeySecretRef:
              name: aws-route53-credsv8
              key: password.txt